# Generated by Django 5.1.5 on 2025-01-21 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="updated_at",
        ),
    ]
